version: '3'

services:
  product-crawler:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - URL_CACHE_TTL_DAYS=7
      - REQUEST_DEFAULT_TIMEOUT=60
      - MAX_WORKERS=10
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data between container restarts
    ports:
      - "27017:27017"
    command: ["mongod", "--quiet"]
    logging:
      driver : "none"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 5
      timeout: 5s

volumes:
  mongodb_data:
